name: mdsoft_google_map_user_pick_location_from_scroll
description: "A powerful Flutter package for real-time navigation and route
  tracking using Google Maps API. This package supports background location
  updates, route calculation, and customizable map styles."
version: 0.0.4
homepage: "https://github.com/Salah3mer/google_map_routing_user_pick_location_from_scroll.git"

environment:
  sdk: ^3.4.2
  flutter: ">=3.3.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_polyline_points: ^3.1.0
  flutter_svg: ^2.3.0
  geocoding: ^4.0.0
  google_maps_flutter: ^2.17.1
  location: ^8.0.1
  toastification: ^3.2.0
  uuid: ^4.5.3
  maps_toolkit: ^3.1.0
  modal_progress_hud_nsn: ^0.5.1
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
  assets:
    - assets/images/
